# Ball Configuration
proportional_controller:
  ros__parameters:
    motor_ids: [35, 36, 37]

euler_integrator_controller:
  ros__parameters:
    motor_ids: [35, 36, 37]

close:
  ros__parameters:
    motor_ids: [35, 36, 37]

open:
  ros__parameters:
    motor_ids: [35, 36, 37]
    motor_position: [100.0, 100.0, 100.0]

slipping_avoidance:
  ros__parameters:
    coefficients: [0.0, 3.3, 0.0, 0.0, 0.0]  # 0.3 friction coefficient
