# Sponge Configuration
proportional_controller:
  ros__parameters:
    motor_ids: [35, 36, 37, 38]

euler_integrator_controller:
  ros__parameters:
    motor_ids: [35, 36, 37, 38]

close:
  ros__parameters:
    motor_ids: [35, 36, 37, 38]

open:
  ros__parameters:
    motor_ids: [35, 36, 37, 38]
    motor_position: [100.0, 100.0, 100.0, 100.0]

slipping_avoidance:
  ros__parameters:
    coefficients: [0.0, 0.0, 0.0, 0.0, 0.0]  # with the sponge slipping avoidance is not used.
